### ISSUE TITLE
Change of IMAP folder names for parsed reports

### ISSUE THREAD

**Issue by jaydee73** [sudo-bot/docker-dmarc-srg#1]
Howdy,

for whatever reason, my email-hoster doesn't allow dots in folder names. Therefore your pre-defined names `DMARC-PROCESSED.Aggregate` and `DMARC-PROCESSED.Invalid` will not work for me.

Is it possible that you change these names or at least make them user-definable via ENV?

AFAIK, the dmarc-srg repo, on which your docker image is based, is also using other folder names for parsed reports.

Thanks,
JD

**Comment by williamdes** [comment]
Hello 👋🏻 

> for whatever reason, my email-hoster doesn't allow dots in folder names. Therefore your pre-defined names DMARC-PROCESSED.Aggregate and DMARC-PROCESSED.Invalid will not work for me.

Okay, I found some dovecot documentation that suggests that in the FS mode they are slashes: https://doc.dovecot.org/configuration_manual/namespace/#core_setting-namespace/separator
So okay for the technical part.

> Is it possible that you change these names or at least make them user-definable via ENV?

Absolutely !

> AFAIK, the dmarc-srg repo, on which your docker image is based, is also using other folder names for parsed reports.

Yeah, I ported my own config into this repo. It is tailored to my current needs that's why ^^

You can open a pull-request if you know how to do that, else I will find some spare time to push an update + this new ENVs

--
William

**Comment by jaydee73** [comment]
Thanks!

To be honest, I'm not familiar with this PR thing and also not with editing code. :-(

So I will patiently wait for some spare time on your side. ;-)

Thanks again,
JD

**Comment by williamdes** [comment]
Done and should work fine ! 🎉 
https://github.com/sudo-bot/docker-dmarc-srg/releases/tag/v1.8-2
Let me know

**Comment by jaydee73** [comment]
Thanks William! I'll tried the new release and it "probably" works. Probably because of a potential misinterpretation on my side. I'll get a "database connection error" in the UI after starting the docker container. Digging a little deeper into this (and taking a look a the dmarcsrg repo) I found out that maybe this docker repo requires an existing mysql-db. I initially thought (and that's what I was searching for) this docker repo is a one-stop-dmarc-solution with an included mysql-db.

**Comment by williamdes** [comment]
> I initially thought (and that's what I was searching for) this docker repo is a one-stop-dmarc-solution with an included mysql-db.

Well, no. But I can help you have a one click solution. Is is quite easy to add a db server.
IIRC DmarcSrg supports sqlite, that would avoid needing a DB server.

Let me know

**Comment by jaydee73** [comment]
That would be awesome if you can add sqlite db to the container!
