### ISSUE TITLE
Does not seem to be fetching mail

### ISSUE THREAD

**Issue by jesseas** [sudo-bot/docker-dmarc-srg#3]
It doesn't seem like this is automatically fetching mail. Looking around it looks like the solution is to add the command `php utils/fetch_reports.php` to a cron job, but it doesn't appear that is set up in the container. 

If I run that command by hand within the container and refresh I see new messages so, as best I can tell, I have everything set up properly.

Am I missing something here? Thanks.

**Comment by riemaeker** [comment]
Same here. Setting up the cron job is trivial, but it seems like a no-brainer to add it to the Dockerfile (maybe with an environment var to specify the fetch interval).

**Comment by williamdes** [comment]
Indeed, this is a documentation mistake on my end
Until now I have this crontab line: `@hourly docker exec dmarc-src php -f utils/fetch_reports.php`
